### ISSUE TITLE
Strong typed actor interface in client project

### ISSUE THREAD

**Issue by DarkHarlock** [OrleansContrib/Orleankka#55]
I've tryed Orlenkka, it is awesome but it lacks of 2 features (maybe there are but I haven't found these).
1. The possibility to have a strong typed proxy in the client side project. I love intellisense, and an Ask or Tell method that take object as parameter doesn't help code writing, the same is for the return value of Ask.
2. To have a common lib with only contracts shared between client and server. I need to share contracts with third parts without any server implementation detail.

In my public repo I've added an example on how to achieve this. 
It requires some patches in Orleankka library (ActorAssembly, Dispatcher, ActorTypeCode and ActorPrototype) and some new interfaces. 
The Client side uses Castle.DinamcProxy to generate on the fly a proxy that implements the actor interface. This proxy forwards messages to an internal ActorRef. 
The server side uses the improved ActorTypeCode and 2 new interfaces (IActorProxyInterface, INonUniformActorProxyInterface). Patches in Dispatcher and ActorAssembly do the magic.

Is it the right way to reach my goal with Orleankka? There are other ways?

**Comment by yevhen** [comment]
Hi DarkHarlock!

Ironically, strongly typed actors were part of Orleankka for a long time, but were [removed](https://github.com/DarkHarlock/Orleankka/commit/d70424cf5750beb26dba8f0e4087e4a72c75e91c) week a ago for the reasons I've described [here](https://gitter.im/yevhen/Orleankka?at=5590489ab4ce4e473250a76e). I've also found issues with having client/server coupling (dependencies) due to inability to have separated interface.

My version of strongly typed actors was based on expression trees, rather than on dynamic proxies. I like it more, since the communication interface is still uniform. Also, it allows you to call non-async members, like fields/properties. Something you can't do with dynamic proxies. Another difference, is that it was allowing to have a *truly* non-uniform interface, such as having a varying number of arguments.

You can take a look and switch to version with typed actors by executing following from command line:
```bash
git co -b typed_actors 43c623f 
```

AFAIR, you don't use lOrleankka's binary version published on Nuget, as it's still contains an implementation of typed actors.

So my version was solving a problem `1)` but not `2)`, and that's exactly what I'm working on now. I'm improving both design and implementation of typed actors, so that:
- Unit testing will be supported
- Separation of strongly-typed interface is possible (separate assemblies)
- Supports having multiple interfaces for the same implementation
- Performance improvements

if you can wait a bit that will be pushed soon (this week, me think). Meanwhile, you can defined message classes for each method and put those in separate assembly. Then, once typed actors are back, you will simply convert those to method signatures and do some inlining, perhaps with automated refactoring tool such as R# (it's really good for that).

**Comment by DarkHarlock** [comment]
Yes, I can wait for this implementation. 
I've already done a little working playground with Orleans so most of the code is written. Now I will try to translate grains in actors adding real CQRS/ES and dependency injection implementation.

Waiting for news, thanks for suggestions.

**Comment by yevhen** [comment]
Hi @DarkHarlock ,

I'm sorry to say but I've decided not to re-implement typed actors. The reasons are:
- They are alien to a functional paradigm direction (with explicit message passing) I've originally chosen for Orleankka. It's completely opposite to original premise of the project.
- It gives a lot of headaches with docs and samples, since I need to duplicate everything two times
- It makes certain things hard or even impossible, thus breaking the original premise of Orleankka again
- It's not really asked by many people. So there is really low ROI (compared to support costs)
- C#7 will arrive in 1 year and will equalize the cost of defining message structs with the cost of defining method signatures. It will also feature discriminated unions which will enable strong typing and IntelliSense for message based interfaces

If absence of IntelliSense is such a big problem for you then I suggest you to turn to use raw Orleans, since type safety (and IntelliSense for that matter) were one of the selling points for them. Not so much for Orleankka.

Regarding separation of interface\implementation - that will be implemented and I'm currently working on this.

P.S. Hope you understand me. I'm very sorry for no meeting your expectations.
Yevhen

**Comment by DarkHarlock** [comment]
Hi @yevhen ,
thanks for your explication.
For now intellisense is not required even if it helps a lot during development. Before C#7, I think that if the intellisense for my actor classes will be quite required a quick tradeoff could be provided by an ad-hoc roslyn analyzer, so I don't care about this.
Orleankka model fits better than Orleans with my needs. Furthermore now you are working on separation of interface/implementation that is for me a strong requirement. These are 2 good reasons to continue with Orleankka.

Bruno

**Comment by yevhen** [comment]
That will be automatically inherited with 1.11 when Orleans drops static codegen, so that we can use native tooling and not cheat with fixed types of grains.

**Comment by yevhen** [comment]
Fixed and tested in 0b03d9ddee2e711e4bf4e83b4a11d5001f091791. Next version of Orleankka will have proper client/server separation
